language: node_js
node_js:
  - "0.11.14"
install: 
  - npm install
  - ./node_modules/bower/bin/bower -v
  - ./node_modules/bower/bin/bower install
  - ln -s /home/vexor/.bower_components app/bower_components
script: ./node_modules/gulp/bin/gulp.js build
